version: '2'
services:
  mariadb:
    build: ./requirements/mariadb/
    image: mariadb
    container_name: mariadb
    env_file: 
      - .env
    restart : always
    volumes:
      - DB:/var/lib/mysql
    networks:
      - net
  nginx:
    build : ./requirements/nginx/
    image : nginx
    container_name: nginx
    env_file:
      - .env
    restart : always
    ports: 
      - 443:443
    expose : 
      - 443
    depends_on :
      - wordpress
    volumes :
      - WordPress:/var/www/html/
    networks:
      - net
  wordpress:
    build : ./requirements/wordpress/
    image : wordpress
    container_name: wordpress
    env_file:
      - .env
    restart : always
    depends_on :
      - mariadb
    volumes :
      - WordPress:/var/www/html/
    networks:
      - net
volumes:
  DB:
    driver : local
    driver_opts:                             
      o: bind                                
      type: none                             
      device: /home/mohtakra/Desktop/data/db 
  WordPress:
    driver : local
    driver_opts:                             
      o: bind                                
      type: none                             
      device: /home/mohtakra/Desktop/data/wordpress 

networks :
  net:
    driver : bridge