version: "3.7"
services:
  alva_mariadb_img:
    build: ./requirements/mariadb/
    image: alva_img_db
    container_name: alva_cont_db
    env_file: 
      - .env
    restart : always
    ports:
      - "3306:3306"
    expose:
      - 3306
    volumes:
      - DB:/var/lib/mysql
    networks:
      - net
  alva_nginx_img:
    build : ./requirements/nginx/
    image : alva_img_nginx
    container_name: alva_cont_nginx
    env_file:
      - .env
    restart : always
    ports: 
      - "443:443"
    expose : 
      - 443
    volumes :
      - WordPress:/var/www/html/
    networks:
      - net
  alva_wp_img:
    build : ./requirements/wordpress/
    image : alva_img_wp
    container_name: alva_cont_wp
    env_file:
      - .env
    restart : always
    volumes :
      - WordPress:/var/www/html/
    networks:
      - net
volumes:
  DB:
    driver : local
    # driver_opts:                             #********************
    #   o: bind                                #i should remove commets in vm
    #   type: none                             #********************
    #   device: /home/mohtakra/Desktop/data/db #********************
  WordPress:
    driver : local
    # driver_opts:                             #********************
    #   o: bind                                #i should remove commets in vm
    #   type: none                             #********************
    #   device: /home/mohtakra/Desktop/data/wordpress #********************

networks :
  net:
    driver : bridge