version: "3"
services:
  alva_mariadb_img:
    build: ./requirements/mariadb/
    container_name: alva_cont_db
    image: alva_img_db
    env_file: 
      - .env
    restart : always
    expose :
      - '3306'
    volumes:
      - data_db:/var/lib/mysql
volumes:
  data_db:
    driver : local
    driver_opts:
      type: none
      o: bind