version: "3.7"
services:
  alva_mariadb_img:
    build: ./requirements/mariadb/
    image: alva_img_db
    container_name: alva_cont_db
    env_file: 
      - .env
    restart : always
    expose :
      - '3306'
    volumes:
      - data_db:/var/lib/mysql
volumes:
  data_db:
    driver : local
    # driver_opts:                             #********************
    #   o: bind                                #i should remove commets in vm
    #   type: none                             #********************
    #   device: /home/mohtakra/Desktop/data/db #********************