version: "2"
services:
  alva_mariadb_img:
    build: ./requirements/mariadb/
    image: alva_img_db
    container_name: mariadb
    env_file: 
      - .env
    restart : always
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - DB:/var/lib/mysql
    networks:
      - net
  alva_nginx_img:
    build : ./requirements/nginx/
    image : alva_img_nginx
    container_name: nginx
    env_file:
      - .env
    restart : always
    ports: 
      - 443:443
    expose : 
      - 443
    depends_on :
      - alva_wp_img
    volumes :
      - WordPress:/var/www/html/
    networks:
      - net
  alva_wp_img:
    build : ./requirements/wordpress/
    image : alva_img_wp
    container_name: wordpress
    env_file:
      - .env
    restart : always
    depends_on :
      - alva_mariadb_img
    expose : 
      - 9000
    ports : 
      - 9000:9000
    volumes :
      - WordPress:/var/www/html/
    networks:
      - net
volumes:
  DB:
    driver : local
    # driver_opts:                             #********************
    #   o: bind                                #i should remove commets in vm
    #   type: none                             #********************
    #   device: /home/mohtakra/Desktop/data/db #********************
  WordPress:
    driver : local
    # driver_opts:                             #********************
    #   o: bind                                #i should remove commets in vm
    #   type: none                             #********************
    #   device: /home/mohtakra/Desktop/data/wordpress #********************

networks :
  net:
    driver : bridge